### ISSUE TITLE
Binary distribution?

### ISSUE THREAD

**Issue by fatuhoku** [somegeekintn/SimDirs#3]
iOS Developers will find this insanely useful but might not have joined the Mac development programme to build this project!

**Comment by somegeekintn** [comment]
It isn't necessary to be in the Mac development program to build this project. All that's required is Xcode.

**Comment by axnmax** [comment]
Now with Xode 6.2 the documents directory is not visible.

**Comment by wvdk** [comment]
Was a decision made on this? I could build and submit a PR with a binary distribution if it'd be helpful. This little app is pretty handy, thanks for making it. :)

**Comment by somegeekintn** [comment]
Forgot all about it actually, but given the target audience it doesn't feel like it's necessary. Oh and you're welcome :)
