### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by informatimago** [somegeekintn/SimDirs#5]
Hi!

You don't mention any license you're distributing this program under.
The source code only contains the copyright notice with 'All rights reserved', which leaves us no right.

I would like to use this code (and transform it into a CLI) for internal use. (I don't plan to distribute it, but depending on the license, I would contribute my modifications back to you, or not).
What under what license would let me do that?

**Comment by somegeekintn** [comment]
I added the MIT license to the project. Hopefully that works for you.

**Comment by informatimago** [comment]
On 21/03/16 16:23, Casey Fleser wrote:
>
> I added the MIT license to the project. Hopefully that works for you.
>
Yes, that's fine. Thank you.

-- 
__Pascal J. Bourguignon__
http://www.informatimago.com/
