### ISSUE TITLE
 App Crashs before it  opens in OS X - 10.11.4

### ISSUE THREAD

**Issue by sandeep12** [somegeekintn/SimDirs#6]
App crashes before it opens in new updated mac os

**Comment by somegeekintn** [comment]
If you could run it under Xcode and let me know where it crashes that would be a big help.

**Comment by cjazz** [comment]
v0.4.4 Crashed, but the last 3 commits look like they may have addressed the issue.  I ran the latest build in Xcode, and no crash 👍.  Thanks for the commits forward.  BTW: I'm running 10.11.6.
